notification:
  email:
    enabled: true
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    from_email: "aditya@kodekloud.com"  # ⚠️ CHANGE THIS TO YOUR EMAIL
    to_emails:
      - "aditya@kodekloud.com"  
      - "gordon@kodekloud.com" 
      - "shafaq@kodekloud.com" 
      - "aakash@kodekloud.com" 
      - "michael@kodekloud.com" 
      - "mmumshad@kodekloud.com" 
  slack:
    enabled: false  # Set to true if you want Slack notifications
    webhook_url: ""  # Will be set via environment variable
  
  discord:
    enabled: false
    webhook_url: ""

# How far back to check for updates (in days)
lookback_days: 7

# Filtering
filters:
  min_relevance: 60
  exclude_keywords: []
  include_certs: []  # Leave empty to monitor all certs
