# RSS Feeds - Comprehensive certification monitoring
# Focus: Specific exam announcements, avoid generic posts

rss_feeds:
  # ============================================
  # AWS CERTIFICATIONS
  # ============================================
  aws:
    - url: "https://aws.amazon.com/blogs/training-and-certification/feed/"
      name: "AWS Training & Certification Blog"
      keywords:
        # Specific exam action keywords
        - "retiring on"
        - "available on"
        - "launching on"
        - "exam retiring"
        - "beta exam"
        - "new exam version"
        - "exam update for"
        - "exam changes for"
        - "new name for"
        - "renamed to"
        - "replacement for"
        - "retirement date"
        # AWS cert codes with version
        - "CLF-C02"
        - "CLF-C03"
        - "Cloud Practitioner exam"
        - "SAA-C03"
        - "SAA-C04"
        - "Solutions Architect Associate exam"
        - "DVA-C02"
        - "DVA-C03"
        - "Developer Associate exam"
        - "SOA-C02"
        - "SOA-C03"
        - "SysOps Administrator exam"
        - "DOP-C02"
        - "DOP-C03"
        - "DevOps Engineer Professional exam"
        - "SAP-C02"
        - "Solutions Architect Professional exam"
        - "ANS-C01"
        - "Advanced Networking exam"
        - "SCS-C02"
        - "Security Specialty exam"
        - "DAS-C01"
        - "Data Analytics exam"
        - "MLS-C01"
        - "Machine Learning Specialty exam"
        - "MLA-C01"
        - "Machine Learning Associate exam"
        - "AIF-C01"
        - "AI Practitioner exam"
        - "PAS-C01"
        - "SAP on AWS exam"

  # ============================================
  # MICROSOFT AZURE CERTIFICATIONS
  # ============================================
  azure:
    - url: "https://techcommunity.microsoft.com/t5/microsoft-learn-blog/bg-p/MicrosoftLearnBlog/feeds/blogposts"
      name: "Microsoft Learn Blog"
      keywords:
        # Specific exam actions
        - "exam is retiring"
        - "exam will retire"
        - "retirement date"
        - "exam update"
        - "new exam"
        - "exam version"
        - "beta exam"
        - "exam changes"
        - "objectives updated"
        - "skills measured updated"
        - "exam retiring on"
        # Administrator track
        - "AZ-104 exam"
        - "AZ-104:"
        - "Azure Administrator exam"
        # Developer track
        - "AZ-204 exam"
        - "AZ-204:"
        - "Developing Solutions for Microsoft Azure"
        # Architect track
        - "AZ-305 exam"
        - "AZ-305:"
        - "Azure Solutions Architect Expert"
        # DevOps track
        - "AZ-400 exam"
        - "AZ-400:"
        - "DevOps Solutions exam"
        # Security track
        - "AZ-500 exam"
        - "AZ-500:"
        - "Azure Security Technologies"
        - "SC-100 exam"
        - "SC-200 exam"
        - "SC-300 exam"
        - "SC-400 exam"
        - "SC-900 exam"
        # Network track
        - "AZ-700 exam"
        - "AZ-700:"
        - "Azure Network Engineer"
        # Fundamentals
        - "AZ-900 exam"
        - "AZ-900:"
        - "Azure Fundamentals exam"
        # Data track
        - "DP-203 exam"
        - "DP-300 exam"
        - "DP-420 exam"
        - "DP-900 exam"
        - "Azure Data Fundamentals"
        # AI track
        - "AI-102 exam"
        - "AI-102:"
        - "Azure AI Engineer"
        - "AI-900 exam"
        - "Azure AI Fundamentals"
        # Microsoft 365
        - "MS-102 exam"
        - "MS-900 exam"
        # Power Platform
        - "PL-100 exam"
        - "PL-200 exam"
        - "PL-300 exam"
        - "PL-400 exam"
        - "PL-500 exam"
        - "PL-600 exam"
        - "PL-900 exam"
    
    - url: "https://learn.microsoft.com/api/search/rss?locale=en-us&%24filter=scopes%2Fany(t%3A%20t%20eq%20%27Certifications%27)"
      name: "Microsoft Learn Certifications Feed"
      keywords:
        - "exam retiring"
        - "retirement"
        - "new exam"
        - "exam update"
        - "beta exam"
        - "AZ-"
        - "AI-"
        - "DP-"
        - "SC-"
        - "MS-"
        - "PL-"

  # ============================================
  # KUBERNETES & CNCF CERTIFICATIONS
  # ============================================
  kubernetes:
    - url: "https://www.cncf.io/feed/"
      name: "CNCF Blog"
      keywords:
        # Kubernetes Foundation Certs
        - "CKA"
        - "CKA exam"
        - "Certified Kubernetes Administrator"
        - "CKAD"
        - "CKAD exam"
        - "Kubernetes Application Developer"
        - "CKS"
        - "CKS exam"
        - "Kubernetes Security Specialist"
        - "KCNA"
        - "KCNA exam"
        - "Kubernetes and Cloud Native Associate"
        - "Cloud Native Associate"
        - "KCSA"
        - "KCSA exam"
        - "Cloud Native Security Associate"
        - "Kubernetes certification"
        # Exam updates
        - "exam update"
        - "certification update"
        - "exam changes"
        - "kubernetes version"
        - "curriculum update"
        - "exam objectives"
    
    - url: "https://training.linuxfoundation.org/feed/"
      name: "Linux Foundation Training"
      keywords:
        # Kubernetes certs
        - "CKA"
        - "CKA exam"
        - "CKAD"
        - "CKAD exam"
        - "CKS"
        - "CKS exam"
        - "KCNA"
        - "KCNA exam"
        - "KCSA"
        - "KCSA exam"
        # Linux certs
        - "LFCS"
        - "LFCS exam"
        - "Linux Foundation Certified System Administrator"
        # CNCF Project certs
        - "PCA"
        - "PCA exam"
        - "Prometheus Certified Associate"
        - "ICA"
        - "ICA exam"
        - "Istio Certified Associate"
        - "CCA"
        - "CCA exam"
        - "Cilium Certified Associate"
        - "OTCA"
        - "OTCA exam"
        - "OpenTelemetry Certified Associate"
        - "KCA"
        - "KCA exam"
        - "Kyverno Certified Associate"
        - "CAPA"
        - "CAPA exam"
        - "Certified Argo Project Associate"
        - "Argo Project Associate"
        - "CGOA"
        - "CGOA exam"
        - "GitOps Certified Associate"
        - "CBA"
        - "CBA exam"
        - "Certified Backstage Associate"
        - "Backstage Associate"
        - "CNPA"
        - "CNPA exam"
        - "Cloud Native Platform Engineering"
        # Generic updates
        - "certification exam"
        - "exam update"
        - "certification update"
        - "exam changes"

  # ============================================
  # GOOGLE CLOUD CERTIFICATIONS
  # ============================================
  google_cloud:
    - url: "https://cloud.google.com/blog/topics/training-certifications/rss"
      name: "Google Cloud Training & Certifications"
      keywords:
        - "Cloud Digital Leader"
        - "Cloud Digital Leader exam"
        - "Professional Cloud Architect"
        - "Professional Cloud Developer"
        - "Professional Cloud Engineer"
        - "Associate Cloud Engineer"
        - "certification exam"
        - "exam update"
        - "exam retiring"
        - "new exam"
        - "beta exam"
        - "certification update"

  # ============================================
  # HASHICORP CERTIFICATIONS
  # ============================================
  hashicorp:
    - url: "https://www.hashicorp.com/blog/feed"
      name: "HashiCorp Blog"
      keywords:
        - "Terraform Associate"
        - "Terraform certification"
        - "Terraform Certified"
        - "Vault Associate"
        - "Vault certification"
        - "Vault Certified"
        - "Vault Operations Professional"
        - "Consul Associate"
        - "Consul certification"
        - "Consul Certified"
        - "certification update"
        - "certification exam"
        - "exam update"
        - "exam changes"

  # ============================================
  # DOCKER CERTIFICATIONS
  # ============================================
  docker:
    - url: "https://www.docker.com/blog/feed/"
      name: "Docker Blog"
      keywords:
        - "Docker Certified Associate"
        - "DCA"
        - "DCA exam"
        - "Docker certification"
        - "certification exam"
        - "exam update"

  # ============================================
  # PYTHON CERTIFICATIONS
  # ============================================
  python:
    - url: "https://www.python.org/blogs/feed/"
      name: "Python Blog"
      keywords:
        - "PCAP"
        - "PCAP exam"
        - "Python Certification"
        - "Python Institute"
        - "certification exam"

  # ============================================
  # COMPTIA CERTIFICATIONS
  # ============================================
  comptia:
    - url: "https://www.comptia.org/blog/feed"
      name: "CompTIA Blog"
      keywords:
        - "Security+"
        - "Security Plus"
        - "SY0-701"
        - "SY0-601"
        - "SY0-801"
        - "Security+ exam"
        - "exam update"
        - "exam retiring"
        - "new version"
        - "certification update"

  # ============================================
  # LINUX PROFESSIONAL INSTITUTE
  # ============================================
  lpi:
    - url: "https://www.lpi.org/blog/feed"
      name: "Linux Professional Institute"
      keywords:
        - "LPIC-1"
        - "LPIC-2"
        - "LPIC-1 exam"
        - "101-500"
        - "102-500"
        - "exam update"
        - "certification update"

  # ============================================
  # FINOPS FOUNDATION
  # ============================================
  finops:
    - url: "https://www.finops.org/feed/"
      name: "FinOps Foundation"
      keywords:
        - "FinOps Certified Practitioner"
        - "FinOps certification"
        - "FinOps exam"
        - "certification exam"
        - "exam update"

  # ============================================
  # GITHUB CERTIFICATIONS
  # ============================================
  github:
    - url: "https://github.blog/feed/"
      name: "GitHub Blog"
      keywords:
        - "GitHub Actions certification"
        - "GitHub Actions Certified"
        - "GitHub Copilot certification"
        - "GitHub Copilot Certified"
        - "GitHub certification"
        - "certification exam"
        - "exam"

  # ============================================
  # JENKINS CERTIFICATION
  # ============================================
  jenkins:
    - url: "https://www.jenkins.io/node/feed.xml"
      name: "Jenkins Blog"
      keywords:
        - "Certified Jenkins Engineer"
        - "CJE"
        - "Jenkins certification"
        - "certification exam"
        - "exam"

  # ============================================
  # NVIDIA CERTIFICATIONS
  # ============================================
  nvidia:
    - url: "https://blogs.nvidia.com/feed/"
      name: "NVIDIA Blog"
      keywords:
        - "Gen AI Certification"
        - "NVIDIA certification"
        - "NVIDIA Certified"
        - "AI certification"
        - "certification exam"

# ============================================
# ANNOUNCEMENT PAGES - Official Update Pages
# ============================================
announcement_pages:
  aws:
    - url: "https://aws.amazon.com/certification/coming-soon/"
      name: "AWS Certification Coming Soon"
      check_for:
        - "Retiring"
        - "Launching"
        - "Available"
        - "Beta"
        - "New"
        - "Updated"
  
  azure:
    - url: "https://learn.microsoft.com/en-us/certifications/"
      name: "Microsoft Certifications Homepage"
      check_for:
        - "retiring"
        - "updated"
        - "new exam"
        - "beta"
        - "AZ-"
        - "AI-"
        - "DP-"
        - "SC-"
  
  linux_foundation:
    - url: "https://training.linuxfoundation.org/certification/"
      name: "Linux Foundation Certifications"
      check_for:
        - "KCNA"
        - "KCSA"
        - "CKA"
        - "CKAD"
        - "CKS"
        - "LFCS"
        - "PCA"
        - "update"
        - "exam changes"
        - "new"
    
    - url: "https://www.cncf.io/certification/"
      name: "CNCF Certifications Page"
      check_for:
        - "KCNA"
        - "KCSA"
        - "update"
        - "announcement"
        - "new"
  
  google_cloud:
    - url: "https://cloud.google.com/learn/certification"
      name: "Google Cloud Certifications"
      check_for:
        - "retiring"
        - "new exam"
        - "updated"
        - "beta"
  
  hashicorp:
    - url: "https://www.hashicorp.com/certification"
      name: "HashiCorp Certifications"
      check_for:
        - "Terraform"
        - "Vault"
        - "Consul"
        - "update"
        - "new"
